# Generated by Django 5.0.7 on 2024-07-26 10:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='session_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['-duration'], name='records_stu_duratio_5987e7_idx'),
        ),
    ]
