# Build stage
FROM node:18.19.1 as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm install -g @angular/cli
RUN ng build --prod

# Run stage
FROM nginx:alpine
COPY --from=build /app/dist/on_focus /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
