version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
