version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "80:4200"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    restart: unless-stopped

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
# docker run -it --rm -p 4200:4200 -v $(pwd)/frontend:/app --network on_focus_mynetwork frontend-image ng serve --host 0.0.0.0 --port 4200
